- .gitignore
- src/App.js
- src/components/Error/Error.jsx
- src/components/common/Title.jsx
- src/components/common/roomOptions/SubmitButton.jsx
- src/components/common/utils/Spacer.jsx
Error Page의 임시 구현
It closes #144
- Error Set을 만들어서 Set 내부에서 선택할 수 있게 제작 (Error Set정의 논의 필요)
- Error Page에 state를 넘겨 주기 위한 global state 적용 필요
- Error Hanler에서 쉽게 Error Page로 필요한 Telemetry 이후 Redirect 할 수 있는 Component 필요
- i18n 도입으로 한글 / 영어 동시 지원 필요
> #144 create error handling page

- src/components/common/modal/Modal.jsx
It closes #181 
공통으로 사용할 수 있는 modal 컴포넌트를 만듭니다.
#Images
- maxWidth="325px"의 prop을 사용한 경우
- default 값은 maxWidth="100%"의 prop을 사용한 경우
- common modal 컴포넌트에서 사용할 수 있는 버튼 컴포넌트 만들기
> #181 Create common modal component

- .env.example
- src/components/Chatting/Chatting.jsx
- src/serverconf.js
It fixes #178 and fixes https://github.com/sparcs-kaist/taxi-back/issues/111
`/api`로 끝나는 주소로 온 요청을 백엔드로 전달하는 reverse proxy를 설정한 뒤 클라이언트에서 소켓 연결을 시도할 때 기본 네임스페이스(`/`)가 아닌 서버에서 정의되지 않은 네임스페이스(`/api` 등)로 연결을 시도하는 문제가 발생했습니다.
문제를 해결하기 위해 클라이언트에 Socket.io 서버의 주소를 저장하는 `ioServer` 변수를 추가해 무조건 기본 네임스페이스(`/`)로 연결을 시도하도록 수정했습니다.
`ioServer`의 값은 `REACT_APP_IO_URL` 환경변수가 설정되어 있다면 그 값으로, 설정되어 있지 않다면 백엔드 주소(`REACT_APP_BACK_URL` 환경변수의 값)으로 설정했습니다.
따라서 메인 브랜치 머지 이후에도 리버스 프록시 없이 서버를 구동한다면(e.g.) 로컬에서 테스트) 환경변수를 추가할 필요는 없습니다.
#178 브랜치의 변경 사항을 아래 주소에서 테스트해보실 수 있습니다.
https://taxi-test.withsang.com/
- 없음.
> [Bug] Socket.io handshake is not established under reverse proxy

- src/components/Myroom/Myroom.jsx
- src/components/Search/SideResult.jsx
- src/hooks/usePageFromSearchParams.tsx
`usePageFromSearchParams` Hook 의 리펙토링 제안드립니다... !!
- `location.search`이 `string` 값이라 `JSON.stringify`로 안 덮어 씌워도 될 것 같습니다
- `usePageFromSearchParams` 파리미터로 `totalPages`를 추가하여 `totalPages` 관련 중복적인 코드와 `useEffect`를 제거하였습니다
#302  로 머지 요청드리는 PR 입니다.
(그래서 approve 제한이 없습니당)
It closes #300
> #300 pagination hook 리펙토링 제안

- src/components/Chatting/MessagesBody/MessagesBody.jsx
날짜가 바뀌었는데 `chatsCache`에 채팅이 있을 경우 우선 `list`에 push하고 `chatsCache`를 null로 초기화합니다. (L66-76)
추가로 `ChatSet`의 길면서 공통된 props들을 분리했습니다.
It closes #395
> #395 bug chatting next date

- src/components/common/roomOptions/DatePicker.jsx
날짜를 오늘로부터 14일 후까지만 선택할 수 있도록 함
- 월 이동 아이콘 및 관련 함수 제거
- 아이콘이 사라지며 height가 작아지길래 padding값을 추가했습니다
- 불필요해진 state, 함수 제거
It closes #406 
- 이번달
- 중간에 다음달로 넘어갈 경우
> Refactor: 날짜 선택 가능일을 현재로부터 14일까지로 변경

- src/serverconf.js
- src/tools/trans.js
It closes #447
react-inject-env가 S3 버킷 주소 환경변수를 추가할 수 있게 process.env를 `serverconf.js`에서 정의한 env로 대체합니다.
로컬에서 환경변수 로딩 잘 되는 모습입니다.
- 없음.
> [Bug] 프로덕션 환경에서 REACT_APP_S3_URL 환경변수 주입 안됨

- public/firebase-messaging-sw.js
It closes #483
기존 FCM message payload의 Notification에 담겨있던 title과 body를 data로 이동시킵니다 (android 앱과의 호환성 확보를 위해서입니다).
없음 (알림 수신이 이전처럼 잘 됩니다!)
- 없음
> #483 FCM background 메시지 핸들러 변경

- src/components/ModalPopup/Body/BodyRoomShare.tsx
- src/tools/moment.js
It closes #547 
다른 플랫폼(예시: 에브리타임 택시 게시판, 손편지 등)에 방 정보를 공유할 수 있도록 아래와 같은 텍스트를 복사하는 기능을 제공합니다.
> 🚕 4월 26일 수요일 오전 2:50 갤러리아 타임월드 → 택시승강장 택시팟 구합니다!
> 🚕 참여 링크: http://localhost:3000/invite/644810b9e2724833e48b20af
기존에 잘 만들어진 링크 복사 기능을 약간만 발전시켰습니다. 👍 
(방 공유 화면 스크린샷)
- 없음.
> #547 방 공유하기에 에브리타임에 글을 올릴 수 있는 템플릿 생성 후 복사 기능 추가

- src/hooks/usePageFromSearchParams.tsx
- src/pages/Home/RoomList.tsx
- src/pages/Home/RoomSection.tsx
It closes #569 
- 모달을 열고 닫는 방식을 통일할 필요가 있어보여요. 홈페이지에서는 페이지를 이동하여 params로 roomId를 확인하는 반면에 검색 페이지에서는 일반 state로 관리하고 있어서 추후 혼란을 초래할 것만 같은 느낌적인 느낌.
> #569 [Bug] 홈페이지 - 방 클릭 시 페이지가 1로 초기화

- src/tools/trans.js
It closes #545 
`getDynamicLink`  함수에 앱이 설치되어 있지 않은 경우 앱스토어로 이동하도록 `appStoreId`를 추가하였습니다.
> #545.3 IOS 기기 모바일에서 홈 페이지 접근 시, 택시 앱 유도 창 띄우기

- src/components/Skeleton/index.tsx
It closes #580 
App에서 `SuggestAppTopBar`이 띄어지는 버그를 해결합니다.
> #580.2 App에서 `SuggestAppTopBar`이 띄어지는 버그 해결

- src/components/Skeleton/index.tsx
It closes #580 
App에서 `SuggestAppTopBar`이 띄어지는 버그를 해결합니다.
> #580.3 App에서 SuggestAppTopBar이 띄어지는 버그 해결

- src/hooks/skeleton/useFlutterEventCommunicationEffect.tsx
- src/hooks/skeleton/useVirtualKeyboardDetectEffect.tsx
- src/hooks/useFetchRecoilState/index.tsx
It closes #580 
Flutter에서 이벤트 호출 전 `isApp` 인식 실패 버그를 해결하였습니다.
> #580.4 Flutter에서 이벤트 호출 전 `isApp` 인식 실패 버그 해결 

- src/components/Link/LinkCopy.tsx
It closes #580 
`IOS` 앱 기기에서 `LinkCopy`가 작동하지 않는 버그를 해결하였습니다.
> #580.5 `IOS` 앱 기기에서 `LinkCopy`가 작동하지 않는 버그 해결

- .env.example
- src/tools/loadenv.ts
- src/types/env.d.ts
It closes #651 
`eventMode`의 값을 개발용 서버에서 변경해 테스트할 수 있게 하기 위해서 `eventMode` 값을 `REACT_APP_EVENT_MODE` 환경변수에 의해 설정될 수 있게 수정합니다.
`process.env.REACT_APP_EVENT_MODE`="2023fall"
- 없음.
> `eventMode` 환경변수로 분리

- src/pages/Home/EventSection/index.tsx
It closes #680 
한가위 송편 이벤트 결과 공지 섹션을 홈페이지에서 더이상 보여주지 않습니다.
> #680.2 한가위 송편 이벤트 결과 공지 섹션 제거

- packages/web/src/components/ModalPopup/ModalCredit.tsx
- packages/web/src/pages/Mypage/langs/en.json
- packages/web/src/pages/Mypage/langs/ko.json
> [FIX] Credit "2024 봄학기 새터반 택시대제전 이벤트"를 만든 사람들의 순서를 전체 바로 다음에 오도록 수정

- packages/web/src/atoms/loginInfo.ts
- packages/web/src/components/Event/SuggestJoinEventContainer/index.tsx
- packages/web/src/components/ModalPopup/ModalEvent2024SpringJoin.tsx
- packages/web/src/components/ModalPopup/index.tsx
- packages/web/src/components/Skeleton/Routes.tsx
- packages/web/src/pages/Home/EventSection/EventSection2024Spring.tsx
- packages/web/src/pages/Home/index.tsx
ModalEvent2024SpringJoin 파일을 신규 생성하고 전화번호, 새터반, 추천인을 입력할 수 있도록 수정했습니다.
SuggestJoinEventContainer에서 ModalEvent2024SpringJoin을 불러오도록 수정했습니다.
> 새터반 택시대제전 이벤트 참여 모달 제작

- packages/web/src/components/Chat/MessagesBody/MessageSet/index.tsx
- packages/web/src/components/ModalPopup/Body/BodyChatReportSelectType.tsx
- packages/web/src/components/ModalPopup/Body/BodyChatReportSelectUser.tsx
- packages/web/src/components/ModalPopup/ModalChatReport.tsx
It closes #757 
- 채팅방에서 프로필 이미지 클릭 시, 신고하기 모달 띄우기 (신고하기 모달의 첫번째 단계는 건너뛰는 것으로 협의하였습니다. @intaericky)
- 신고하기 모달의 두번째 단계에서 이전 버튼 클릭 시, 첫번째 단계로 돌아가 전에 선택했었던 유저를 선택한 상태로 표시
- 신고 리스트에서 자기 자신 제거
https://github.com/sparcs-kaist/taxi-front/assets/48019789/ed03b8dd-f321-4956-99cf-c7f9ee967e84
> 프로필 이미지 클릭 시 신고 모달 띄우기

- packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx
It closes #778 
packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx 를 수정하여,
1) 이미 참여 중인 방의 경우에도 활성화된 버튼이 나타나도록 하였으며
2) requestJoin 을 수정하여, 해당 버튼을 누르면 history.push를 사용하여 바로 방으로 이동하는 로직을 추가하였습니다.
requestJoin을 수정하면서, 이미 참여 중인 방은 API 호출이 필요 없기에 기존의 코드를 모두 무시하도록 하였습니다. requestJoin의 수정 사항이 적절한지를 중심으로 리뷰해주시면 감사하겠습니다.
1. 홈에서 모달을 띄운 채로 다른 창에서 탑승 취소해버리면, 추후에 모달에서 버튼을 누르면 방 참여(또는 존재) 여부를 검증하지 않고 url을 이동하기에 무한 로딩이 뜹니다. 이것을 검증하기 위해 API 콜을 날리는 게 좋은지, 아니면 이런 극단적인 경우를 위해 API 콜을 낭비하지 않는 게 좋은지 논의하고 싶습니다.
2. 11시 10분 출발 방은 11시 10분 59초까지 홈 화면에 보이는 것 같습니다. 이로 인해 홈 화면에 보이지만, isDepart로 인해 (참여 중인 경우의 바로가기 버튼도 포함) 버튼이 비활성화 되어 있는 상태가 1분간 지속됩니다. 이것이 새로운 이슈로서 논의되어야 할 것 같습니다.
우선은 이 PR에 대한 추가 커밋을 통해, 그 1분 동안 이미 참여한 방이라면 비활성화 버튼 대신 바로가기 버튼이 뜨도록 하는 코드를 올려두었습니다.
> #778 홈 화면 방 팝업에서 참여 중인 방 선택 시 바로가기 버튼 추가

- packages/web/src/hooks/skeleton/useChannelTalkEffect/channelService.js
- packages/web/src/hooks/skeleton/useChannelTalkEffect/index.tsx
- packages/web/src/pages/Mypage/Menu.tsx
- packages/web/src/pages/Mypage/index.tsx
- packages/web/src/pages/Mypage/langs/en.json
- packages/web/src/pages/Mypage/langs/ko.json
It closes #767 
[https://developers.channel.io/reference/web-channelio-kr](url) 채널톡 개발 문서에 의하면 openChat을 통해 message를 미리 채워서 채팅창을 열게 할 수 있다고 합니다. 
앱 환경에서만 보이도록 수정했습니다.
> 회원 탈퇴 채널톡 연결 컴포넌트

- packages/web/src/components/Chat/Header/SideMenu.tsx
- packages/web/src/components/Chat/MessagesBody/MessageSet/index.tsx
It closes https://github.com/sparcs-kaist/taxi-front/issues/781
함께 탑승하는 인원이 없을 때(혼자일 때), 신고하기 기능 제거
- 햄버거 메뉴의 신고하기 버튼 hide
- 프로필 이미지 클릭해도 신고하기 모달 뜨지 않음
> 함께 탑승하는 인원이 없을 때, 신고하기 기능 제거

- packages/web/src/components/ModalPopup/Body/BodyAccountCancelProcess.tsx
- packages/web/src/components/ModalPopup/ModalAccountCancelProcess.tsx
- packages/web/src/components/ModalPopup/index.tsx
- packages/web/src/pages/Mypage/index.tsx
It closes #794 
기한이 오늘까지인 Google Play Store측 요구사항을 만족시키기 위해, 회원 탈퇴 절차를 자세히 명시한 모달을 마이 페이지에 추가하였습니다. 임시 조치이기 때문에 버튼을 통해서는 접근할 수 없고, `/mypage?accountCancelProcess=true` 경로로 접근하는 경우에만 표시됩니다.
추가적으로, Android 앱을 통해 접속한 경우에만 회원 탈퇴 버튼이 표시되도록 변경하였습니다.
- 개인정보 처리방침에 통합
- 실제 회원 탈퇴 기능 구현 (Soft Delete)
> #794 회원 탈퇴 절차 명시

- packages/web/src/components/Room/index.jsx
It closes #798 
`Room` 컴포넌트에서, 방 이름에 해당하는 스타일과 인원 수 태그에 해당하는 스타일을 고쳐서,
- 방 이름은 : flexShrink는 1로, flexGrow는 0으로
- 인원 수 태그는 : 둘 다 0으로
설정하여 태그는 원래의 크기를 항상 유지하며, 방 이름이 카드 크기나 방 이름의 길이에 맞추어 줄어들도록 하였습니다.
테스트를 위해 긴 이름의 방을 생성할 때, 우리가 채팅창에서 긴 채팅은 아예 입력되지 않게 한 것처럼 방 이름도 입력하는 칸에서부터 글자 수 제한을 적용하면 어떨까 합니다 (현재는 올바르지 않은 방 이름이라고 생성 버튼이 비활성화되는 방식입니다)
> #798 방 이름이 길 때 인원수 표시가 찌그러짐

- packages/web/package.json
- packages/web/src/components/Chat/MessageForm/InputText/BodyText.tsx
- packages/web/src/components/Chat/MessageForm/InputText/index.tsx
- packages/web/src/components/Chat/MessagesBody/MessageSet/MessageText.tsx
- packages/web/src/hooks/chat/useSendMessage.tsx
- packages/web/src/tools/regExpTest.js
- pnpm-lock.yaml
It closes #773
140자 길이 제한을 구현하고, 향후 길이 제한을 바꿀 수 있도록 하였으며, react-circular-progressbar를 사용하여 현재 글자 수를 보기 쉽게 나타냅니다.
progressbar의 위치, 크기, margin 등이 과연 적절한가, 전체 리디자인 예정이기는 해도 style 변경 사항이 디자인 시스템의 체계를 너무 갖추지 않은 건 아닌가, state 사용이나 기타 등등 코드의 전체적인 구조와 맞지 않는 점은 없는가, 등을 중점적으로 리뷰해주시면 감사하겠습니다!
1. packages/web/src/tools/regExpTest.js 의 `chatMsgLength` 정규 표현식을 수정합니다.
2. 이에 더해, packages/web/src/components/Chat/MessageForm/InputText/BodyText.tsx 의 `maxChatMsgLength` 변수 값도 함께 수정해 줍니다.
props에 대한 변경 사항을 모두 없애고, BodyText.tsx에서만 해결할 수 있도록 수정하였습니다.
리뷰 내용을 적용하면서, Progress Bar가 아랫쪽에 정렬되게 할 방법을 고민한 결과. BodyText.tsx와 index.tsx의 수정사항을 모두 없앤 후에, (정규 표현식 등의 변경 사항은 그대로입니다) 아래의 사항을 적용하였습니다. 
1. `chatMsgLength`라는 state와 `maxChatMsgLength`라는 변수를 BodyText 안에 선언합니다.
3. CircularProgressBar를 BodyText에서 사용합니다. 즉 이제 BodyText 안에 …
> #773 채팅 140자 넘으면 입력 막기 & 글자 수 circular progress bar로 표시

- packages/web/src/components/Chat/MessageForm/InputText/BodyText.tsx
It closes #809 
Circular bar를 위해 길이를 저장하던 state 값을, onSend에서 0으로 만들어줘야 하는데 빠져 있었습니다. 해당 부분 수정하였습니다.
> [Bug] 채팅에서 메시지 전송 시 글자 수 바가 초기화되지 않는 문제 해결

- packages/web/src/components/ModalPopup/ModalRoomSelection.tsx
It closes #801 
사진과 같이 방 이름에 해당하는 부분의 오른쪽 패딩을 X 버튼 크기만큼 더했습니다.
> [Bug] 방 이름이 너무 길면 방 이름이 X 버튼에 겹침

- packages/web/src/components/Event/CreditAmountStatusContainer/index.tsx
- packages/web/src/components/Event/WhiteContainerShareEvent/index.tsx
- packages/web/src/components/Event/WhiteContainerSuggestShareEvent/index.tsx
- packages/web/src/components/ModalPopup/Body/BodyEvent2024FallShare.tsx
- packages/web/src/components/ModalPopup/ModalEvent2024FallJoin.tsx
- packages/web/src/components/ModalPopup/ModalEvent2024FallShare.tsx
- packages/web/src/components/ModalPopup/index.tsx
- packages/web/src/pages/Event/Event2024Fall.tsx
- packages/web/src/pages/Event/Event2024FallMissions.tsx
- serve/invite-event.html
It closes #824 
이벤트 
1. 이벤트 소개 페이지에 공유하기 섹션을 만들었습니다.
2. 이벤트 공유를 위한 모달을 이번 이벤트에 맞게 수정했습니다.
3. 이벤트 참여를 위한 모달을 해당 추천인 시스템에 맞게 수정하며, 문구도 함께 수정했습니다.
4. 퀘스트 페이지에서도 이벤트 공유를 할 수 있도록 카드를 추가했습니다.
- 카카오톡 공유 시, OG 이미지를 연결하면 좋을 것 같습니다.
> 이벤트 공유하기 기능 각종 수정 사항 구현

- packages/web/src/components/Event/DailyAttendanceCalendar/index.tsx
- packages/web/src/components/Event/WhiteContainerSuggestShareEvent/index.tsx
- packages/web/src/components/ModalPopup/ModalEvent2024FallDailyAttendance.tsx
- packages/web/src/pages/Event/Event2024Fall.tsx
- packages/web/src/pages/Event/Event2024FallDailyAttendance.tsx
modal when event is over
- It closes #832 
- 이벤트가 끝나면 출석체크 모달이나 완료 API 호출 안 되게 버그 픽스함. 
->
> [Bug] 출석 체크 모달 스탬프가 찍히지 않음

- packages/web/src/pages/Home/EventSection/index.tsx
It closes #838
2024 추석 이벤트 결과 공지 섹션을 홈페이지에서 더이상 보여주지 않습니다.
> #838.2 2024 추석 이벤트: 결과 섹션 삭제

- packages/web/src/pages/Home/SelectDate.tsx
It closes #844
SelectDate에서 날짜를 getToday10으로 불러오는데 여기에서 10분 단위로 올림되는 이슈가 있었던 것 같아요. getToday로 바꿔서 해결했습니다
> #844 23:50~00:00 사이에 메인 페이지 접속 시 시간이 잘못 표시되는 이슈 해결

- package.json
- packages/web/src/components/ModalPopup/ModalEvent2025SpringItem.tsx
- packages/web/src/components/ModalPopup/ModalEvent2025SpringRandomBox.tsx
It closes #866
키보드 때문에 구매 수량이 가려지는 문제를 해결하기 위해 input의 위치를 바꿨습니다
또한 100 이하의 수가 입력되면 자동으로 100으로 replace되던 것을 없애고, 대신 100의 배수가 아닐 경우 구매가 안 눌리도록 변경하였습니다.
> 2025 새학기 이벤트 : 랜덤박스 모달 수정

- Dockerfile
- serve/default.conf.template
It closes #869
- [Multi-stage builds](https://docs.docker.com/build/building/multi-stage/) 이용해 사이즈를 2.99GB → 256MB로 줄였습니다. (약 91% 감소)
- ECR에 표시되는 기존 이미지의 사이즈는 1,136MB인데, 이는 압축된 크기입니다. ([Ref.](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-info.html))
> Starting with Docker version 1.9, the Docker client compresses image layers before pushing them to a V2 Docker registry. The output of the **docker images** command shows the uncompressed image size. Therefore, keep in mind that Docker might return a larger image than the image shown in the AWS Management Console.
- 빌드 시간이 단축되었습니다.
- AS-IS
```sh
docker build --no-cache -t taxi-front:latest .  # 3m 31s (0/15 cache)
docker build -t taxi-front:latest .             # 2m 29s (5/15 cache)
```
- TO-BE
```sh
docker build …
```
> #869 [Refactor] Docker 이미지 사이즈 줄이기
