src/components/Frame/DatePicker/DatePicker.jsx
in this pr, I added blank spaces.
=> Making new test branch

.eslintrc.js, package-lock.json, package.json, src/components/Search/Search.jsx, src/components/Search/SearchResult/SearchResult.jsx
I encoded needed information to the url to pass to searchresult page.
=> #25 encode info to url

src/components/Search/Search.jsx, src/components/Search/SearchResult/SearchResult.jsx
1. 시간 선택 시 선택된 시간이 뜨게 하는 것
2. searchresult 페이지에서 쓰게 주소 파싱하는것
=> Fix time selection and parsing in searchpage

src/components/Setting/Setting.jsx
#36 propTypes가 누락돼 오류가 발생하길래 추가했습니다.
=> Fix missing propTypes in Setting.jsx

src/components/Search/Search.jsx
Changed wrong alignment of image components
=> UI alignment

package-lock.json, package.json, src/App.js, src/components/Frame/RoomPlace/RoomPlace.jsx, src/components/Search/SearchOrAdd.jsx, src/components/Search/add_selected.svg
added filters for the room search - search and add should be separated
=> Filter added

src/components/Setting/ModifyModal.jsx
=> Fix bug in nickname change handler

src/App.css, src/components/Frame/BackgroundPurpleContainer/BackgroundPurpleContainer.jsx, src/components/room/Myroom/Myroom.css, src/components/room/Myroom/Myroom.jsx
기존의 페이지는 mobile-layout이라는 class의 div로 감싸고, web을 위한 component를 추가적으로 구성.
whitecontainer는 다른 페이지에서도 많이 사용하기 때문에, web의 각 room을 표시하는 block을 BackgroundPurpleContainer로 새롭게 구성.
web_layout과 mobile_layout은 창 크기별 display를 none으로 바꾸기 위한 것
기존의 lay_auto는 WhiteContainer를 위한 것. 그래서 새롭게 lay_auto2를 만들고, web용 layout에서 자동적으로 좌 우 margin을 설정해주는 역할. 기존의 lay_auto는 web용 layout에서는 좌 우 margin을 관리하지 않다가, mobile용 화면에서 margin을 관리
=> #34 making myroomlist front

src/components/Search/Add.jsx
밑의 pr 과 같이, 입력 상태에 따라 버튼에 나타나는 스트링이 변하도록 코딩.
=> change popup to add button string

package-lock.json, package.json, src/components/Search/Search.jsx
이전까지는 팝업을 사용하여 이용조건이 충족되지 않았음을 표시했는데, 
피그마에 주어진대로 조건 불충족 시 버튼 클릭 비활성화 및 버튼스트링 변화로 바꾸기로 했습니다.
=> change popup to button string change

.github/issue_template.md, .github/pull_request_template.md
This PR adds issue/PR templates for Github.
It closes #104 
- No screenshots are required for this PR.
- No further work required.
=> [WiP] #104 add issue and PR templates

.github/ISSUE_TEMPLATE/issue-template.md
=> Merge main to #104

.github/ISSUE_TEMPLATE/bug-report-template.md
=> Update issue templates

.github/issue_template.md, .github/pull_request_template.md
=> #104 add issue and pr templates

src/components/Chatting/Chatting.jsx
It closes #123 
- Needs more than 2 reviewers? y
=> #123-modify-roomInfo-api-calling

src/components/Search/AddRoom/AddRoom.jsx
=> Fix time not showing properly

src/components/Search/AddRoom/AddRoom.jsx
=> Refactor: modify addRoom api

src/components/Chatting/Chatting.jsx
=> Refactor: modify chatting api

README.md
=> #77 update readme

package-lock.json, package.json, src/App.js, yarn.lock
It closes #156 
For scroll restoration
=> #156 Scroll Restoration

src/components/Frame/DatePicker/getDateInfo.js, src/components/Search/AddRoom/AddRoom.jsx, src/components/Search/Search/Search.jsx, src/tools/trans.js
It closes #139 
- 서버와 시간 동기화 필요 (시간 오차로 back에서 요청이 막히는 경우가 발생할 것 같습니다.)
=> #139 방 개설 페이지 default time 버그

src/components/AddRoom/AddRoom.jsx, src/components/Search/Search.jsx, src/components/Search/SideResult.jsx, src/components/common/roomOptions/Place.jsx, src/hooks/useTaxiAPI.jsx, src/tools/trans.js
It closes #166
장소 관련 정보를 locations API를 통해 가져오고 표시하도록 변경했습니다.
- 한/영 전환 지원
=> #166 change location scheme

src/components/Search/RoomSelectionModal.jsx, src/components/Search/SideResult.jsx, src/components/common/RLayout.jsx, src/components/common/modal/Modal.jsx, src/components/common/room/Room.jsx
It closes #167 
검색 화면에서 선택할 경우 모달에서 방 정보를 띄우고 참여 신청을 할 수 있습니다.
이 때 이미 참여한 방의 경우 참가 버튼을 disable했습니다.
- 에러 핸들링
=> #167 add room modal

src/App.js, src/components/Login/Login.jsx, src/components/Mypage/Mypage.jsx, src/components/Skeleton/ChannelTalk.jsx, src/serverconf.js, src/tools/channelService.js
It closes #190 
채널톡 서비스를 사용하여 문의하기를 할 수 있습니다.
마이페이지에서 "문의하기" 버튼을 클릭시 채널톡 화면이 보여집니다.
- 데스크탑 환경에서 문의하기 버튼을 클릭했을 때
- 모바일 환경에서 마이페이지 기본 화면
- 모바일 환경에서 문의하기 버튼을 클릭했을 때
- 로그인 페이지에서
- 로그인을 하였을 때, 익명이 아닌 로그인 정보를 포함하여 문의하기
=> #190 채널톡 서비스를 사용한 문의하기

package-lock.json, package.json, src/App.js, src/components/Skeleton/Skeleton.jsx, src/components/common/roomOptions/Place.jsx, src/recoil/preference/atom.js, src/recoil/preference/index.js, src/recoil/taxiLocation/atom.js, src/recoil/taxiLocation/index.js, src/recoil/taxiLocation/withName.js, tsconfig.paths.json, yarn.lock
It closes #188 
- 장소를 recoil에서 관리, API를 1회만 요청하도록 변경했습니다.
- 설정 또한 recoil에서 관리하도록 atom을 생성했고, 현재 언어 설정에 따라 장소 이름들을 반환하도록 했습니다. (현재 `ko` default)
- 구조는 [다음 article](https://wes-rast.medium.com/recoil-project-structure-best-practices-79e74a475caa)을 참고했습니다.
- 뷰 변경점 없음
- userId, 스타일 변수 등을 recoil에서 관리
=> #188 introduce global state (location 적용)

src/components/Chatting/Chatting.jsx, src/components/Chatting/Header/FullChatHeader.jsx, src/components/Chatting/Header/Header.jsx, src/components/Chatting/Header/HeaderBody.jsx, src/components/Chatting/Header/Popup/PopupCancel.jsx, src/components/Chatting/Header/Popup/PopupContainer.jsx, src/components/Chatting/Header/Popup/PopupPay.jsx, src/components/Chatting/Header/Popup/PopupSend.jsx, src/components/Chatting/Header/SideChatHeader.jsx, src/components/Myroom/Myroom.jsx, src/components/Myroom/R2Myroom.jsx, src/components/Search/RoomSelectionModal.jsx, src/components/common/modal/Button.jsx, src/components/common/modal/ButtonCancelOk.jsx
It closes #175 
- 택시 출발 전, 탑승 취소 버튼 클릭 시
- 택시 출발 후, 결제 완료 버튼 클릭 시
- 택시 출발 후, 결제 완료 버튼 클릭 후
- 택시 출발 후, 정산 완료 버튼 클릭 시
- 택시 출발 후, 정산 완료 버튼 클릭 후
- 버튼 이름, 아이콘 논의 필요(??)
- 정산 상태, 택시 출발여부 자동 업데이트
=> #175 chatting header refactoring 2

package-lock.json, src/components/AddRoom/AddRoom.jsx, src/components/Chatting/Header/HeaderBody.jsx, src/components/Chatting/MessagesBody/ChatSet.jsx, src/components/Chatting/MessagesBody/MessagesBody.jsx, src/components/Search/RoomSelectionModal.jsx, src/components/Search/Search.jsx, src/components/common/room/Room.jsx, src/components/common/roomOptions/DatePicker.jsx, src/tools/moment.js, src/tools/trans.js, yarn.lock
=> #199 Wrapping moment

src/components/Skeleton/ChannelTalk.jsx, src/tools/channelService.js
It closes #204 
- 채팅 접속 시 401 에러가 발생 중
=> #204 pass user info to channeltalk

src/App.js, src/components/Mypage/PopupMypage/PopupMypage.jsx, src/components/Skeleton/AlertProvider.jsx, src/recoil/alert/atom.js, src/recoil/alert/index.js
It closes #203 
recoil을 사용하여 커스텀 alert 모달을 사용할 수 있습니다.
- Needs more than 2 reviewers? y
=> #203 introduce AlertProvider

src/components/Mypage/ProfileImg.jsx
=> #213-프로필-사진-비율-문제

src/components/Mypage/PopupMypage/PopupMypage.jsx
=> #216-bug-프로필-수정-모달-ui-문제

package-lock.json, package.json, src/components/AddRoom/AddRoom.jsx, src/components/Search/Search.jsx, src/components/common/roomOptions/Date.jsx, src/components/common/roomOptions/DatePicker.jsx, src/components/common/roomOptions/Place.jsx, yarn.lock
It closes #217
- 검색시 url 쿼리를 이용합니다
- 변경된 flow는 아래와 같습니다.
```
/ 혹은 /search
-> 검색 조건 선택
-> 검색 버튼 클릭할 경우 조건을 query에 포함해 새로운 url로 이동
-> url이 변경될 경우 effect 함수 내에서 API 요청
```
- 이제 뒤로가가를 할 경우 검색조건이 유지됩니다.
https://user-images.githubusercontent.com/34625313/189342523-ca7bfbc1-82fc-42ee-b9f2-6acf7a46534f.mov
- query를 다양한 방식으로 활용할 수도 있을 것 같습니다
=> #217 use query on search

package-lock.json, package.json, src/components/Search/Search.jsx, yarn.lock
fix bug #215 by isMobile library
Reference: https://github.com/kaimallea/isMobile
=> #215 모바일 배경색 필터 문제

src/components/Skeleton/ChannelTalk.jsx
It closes #212
- 상담시 이름이 id가 아닌 name으로 표시됩니다
=> fix: change channelio name from id to name

src/components/common/Button.tsx
It closes #240
- 이후 필요할 경우 style 객체에 `React.CSSProperties` 타입 적용
=> fix: style에 React.CSSProperties 타입 적용

.github/pull_request_template.md
It closes #255 
- taxi-back, taxi-app repo에도 동일한 PR 생성 (이 PR 머지되면 동일한 PR back과 front에도 올리겠습니다 !)
=> PR Template 수정

src/components/Chatting/Header/FullChatHeader.jsx, src/components/Chatting/MessagesBody/ImageFullscreen.jsx, src/components/Mypage/PopupMypage/PopupMypage.jsx, src/components/Mypage/PopupSparcs/PopupSparcs.jsx, src/components/Skeleton/Navigation.jsx, src/components/common/HeaderBar.tsx, src/components/common/modal/Modal.jsx, src/components/common/roomOptions/Popup.jsx, src/styles/theme.ts
It closes #257. #248에서 파생된 PR.
=> #257 테마에 zIndex 추가

src/components/AddRoom/AddRoom.jsx, src/components/Error/Error.jsx, src/components/Mypage/Mypage.jsx, src/components/Myroom/R1Myroom.jsx, src/components/Myroom/R2Myroom.jsx, src/components/Search/RoomSelectionModal.jsx, src/components/Search/Search.jsx, src/components/Search/SideResult.jsx, src/components/common/Title.jsx, src/components/common/WhiteContainer.jsx, src/components/common/roomOptions/Date.jsx, src/components/common/roomOptions/MaxPartLength.jsx, src/components/common/roomOptions/Name.jsx, src/components/common/roomOptions/Place.jsx, src/components/common/roomOptions/Time.jsx
=> #259 marginAuto의 default 값 수정

public/robots.txt
=> Refactor: modify robot.txt to prevent crawling

src/components/common/roomOptions/Date.jsx, src/components/common/roomOptions/DatePicker.jsx, src/styles/theme.ts
=> #263 Datepicker 색상 변경

src/components/Search/Search.jsx
It closes #275 
https://user-images.githubusercontent.com/84715637/194708996-fc8c5b1a-1994-4f73-9b38-527fc11113ee.mov
=> #275 검색 조건 순서 변경 및 default 옵션 추가

src/components/common/modal/Modal.jsx, src/components/common/roomOptions/Place.jsx, src/components/common/roomOptions/Popup.jsx, src/components/common/roomOptions/Time.jsx, src/hooks/useDisableScroll.tsx
=> #269 모달 백그라운드 스크롤 막기

src/App.css, src/components/Chatting/MessagesBody/ChatSet.jsx, src/components/Mypage/Mypage.jsx, src/components/Mypage/PopupMypage/PopupMypage.jsx, src/components/Mypage/PopupPolicy/PopupPolicy.jsx, src/components/Mypage/ProfileImg.jsx, src/components/Search/Search.jsx, src/components/Skeleton/Navigation.jsx, src/components/common/Title.jsx, src/styles/theme.ts
It closes #272
- 여러 Modal 수정 작업은 커질거 같아 별도 PR에서 작업 예정
=> #272 마이페이지 스타일링

src/components/AddRoom/FullParticipation.tsx, src/components/Mypage/PopupMembers.jsx, src/components/Mypage/PopupModify.jsx, src/components/Search/SideResult.jsx, src/components/common/room/Room.css, src/components/common/room/Room.jsx, src/styles/theme.ts
It closes #297 
https://user-images.githubusercontent.com/84715637/197564292-655e52f3-533d-4f3f-bb26-9f96c7fb57a8.mov
=> #297 Room 컴포넌트 스타일 수정

.env.example, package-lock.json, package.json, src/components/Skeleton/Skeleton.jsx, src/serverconf.js, yarn.lock
It closes #308 
<p align="left">
</p>
- 로그인, 검색 이벤트도 GA에 추가
=> #308 Introduce google analytics

src/recoil/alert/index.ts
=> #322 [Hotfix] alertAtom path

src/App.css
=> #330 모바일에서 터치 시 뜨는 불필요한 레이어 삭제

src/components/Mypage/Mypage.jsx, src/components/Mypage/PopupModify.jsx
https://github.com/sparcs-kaist/taxi-back/pull/170
위 PR 머지되면 open하겠습니다
- 마이페이지에서 호출하는 userInfoDetail API를 제거하고 recoil state를 사용합니다
- 업데이트할 경우 recoil state를 업데이트합니다.
It closes #321
화면 변경 없음
=> mypage에서  userinfodetail use recoil

src/components/Search/RoomSelectionModal.jsx, src/components/Search/SideResult.jsx, src/components/common/Circle.tsx, src/components/common/DottedLine.tsx, src/components/common/MiniCircle.tsx, src/components/common/modal/Modal.jsx, src/components/common/roomOptions/DatePicker.jsx, src/components/common/roomOptions/Place.jsx
=> #336 RoomSelectionModal 스타일 수정

src/components/Skeleton/Navigation.tsx
=> #341 내 방 채팅창 열려 있을 때 다른 페이지로 이동하지 않는 버그

src/components/AddRoom/AddRoom.tsx, src/components/common/roomOptions/Popup.css, src/components/common/roomOptions/Time.tsx, src/tools/moment.js, src/types/react-mobile-picker-mod.d.ts
=> #340 시간이 0일때 방 개설이 되지 않는 오류

src/components/Search/Search.jsx
It closes #347
https://user-images.githubusercontent.com/34625313/199909510-3bc83fb6-fb76-4f99-98a6-423027639d2c.mp4
=> fix: 검색페이지 moment 날짜 설정 방식 변경

src/components/AddRoom/AddRoom.tsx, src/components/Search/Search.jsx, src/components/common/roomOptions/DatePicker.jsx
=> #348 오늘을 기본 날짜로 선택

src/components/Mypage/PopupModify.jsx
It closes #339 
- `profileImgUrl`과 `profileImageUrl` 중 하나로 통일
=> #339 기본 프로빌 사진 변경 오류

src/components/AddRoom/AddRoom.tsx, src/components/AddRoom/FullParticipation.tsx, src/components/Chatting/SideChat.jsx, src/components/Mypage/Mypage.jsx, src/components/Myroom/R1Myroom.tsx, src/components/Myroom/R2Myroom.jsx, src/components/Reporting/PopupReport.tsx, src/components/Search/Search.jsx, src/components/Search/SideResult.jsx, src/components/Skeleton/AlertProvider.jsx
It closes #332 
화면 변경점 없음
- boolean 속성의 props는 props명에 `is...`를 붙이는 방식으로 통일하면 좋을 것 같네요
=> Refactor: remove true at props

src/components/Chatting/Chatting.jsx, src/components/Chatting/Header/FullChatHeader.jsx, src/components/Chatting/Header/HeaderBody.jsx, src/components/Chatting/Header/Popup/PopupCancel.jsx, src/components/Chatting/Header/Popup/PopupPay.jsx, src/components/Chatting/Header/Popup/PopupSend.jsx, src/components/Myroom/Myroom.jsx, src/components/Myroom/R2Myroom.jsx
=> #352 정산/결제 시 과거 방으로 이동하지 않는 오류

src/components/Chatting/MessagesBody/ChatSet.jsx
=> #359 채팅 분 표시 방식 수정

package-lock.json, package.json, src/App.js, src/components/Mypage/Menu.tsx, src/components/Mypage/Mypage.jsx, src/components/Skeleton/Skeleton.jsx, src/recoil/alert/atom.ts, src/static/betaNotice.js, yarn.lock
=> #365 베타 안내창 띄우기

src/components/common/roomOptions/Picker.js
It closes #363 
- 함수형 컴포넌트로 리팩토링..?
=> #363 Picker 사용성 개선

src/components/common/roomOptions/Picker.css, src/static/betaNotice.js
=> #370 베타 안내창 및 Picker 스타일 수정

src/components/Search/Search.jsx
=> #378 최대 인원 옵션만 켠채로 검색시 방을 반환하지 않는 오류

src/components/AddRoom/AddRoom.tsx, src/components/Mypage/Menu.tsx, src/components/Search/RoomSelectionModal.jsx, src/components/common/roomOptions/Picker.js
=> #375 검색 후 방 참가 시 내 방 목록에 바로 뜨지 않는 오류

src/components/Mypage/PopupModify.jsx, src/components/common/modal/Modal.jsx, src/components/common/roomOptions/Popup.tsx, src/hooks/useKeyboardOperation.tsx
It closes #373 
옵션 Popup과 닉네임 수정 Modal에서 Enter를 누를 경우 선택/수정이 동작하고 Esc를 누를 경우 모달이 닫히게 합니다.
=> 모달, popup에서 Enter, Esc 동작 추가

src/App.css, src/components/Chatting/MessageForm/FullChatMessageForm.jsx, src/components/Chatting/MessagesBody/MessagesBody.jsx, src/components/Myroom/R2Myroom.jsx, src/components/Skeleton/Skeleton.jsx
=> #396 채팅창 및 내 방 목록 스타일링

src/components/common/RLayout.jsx, src/components/common/modal/Modal.jsx
It closes #382 
- 추후 popup과 modal 통합 후 모든 곳에 똑같이 적용
=> #382 모달 예상치 못하게 닫힘

src/components/Chatting/Header/FullChatHeader.jsx, src/components/Chatting/Header/SideChatHeader.jsx, src/components/Myroom/R2Myroom.jsx, src/components/Skeleton/Navigation.tsx, src/components/common/Title.jsx
=> #398 아이콘 수정

src/components/Chatting/Header/FullChatHeader.jsx, src/components/Chatting/MessageForm/MessageForm.tsx, src/components/Skeleton/Footer.jsx, src/components/Skeleton/Skeleton.jsx, src/components/common/HeaderBar.tsx, src/styles/theme.ts
It closes #384 
- 모바일 채팅시 입력 칸 `height` 이슈 해결
=> #384 아이폰 웹앱 사용성 개선

src/components/common/roomOptions/Picker.css, src/components/common/roomOptions/Picker.js, src/components/common/roomOptions/Popup.tsx, src/components/common/roomOptions/Time.tsx
=> #386 키보드 눌렀을 시 Picker focus

src/components/Mypage/Mypage.jsx, src/components/Skeleton/Skeleton.jsx
=> #409 베타 안내창 지우기

src/components/Home/SelectDate.tsx
=> #414 [Bug] Hotfix: 홈페이지 month 표시 수정

.github/workflows/push_image_ecr.yml, .github/workflows/push_image_ecr_dev.yml, Dockerfile, README.md
=> #304.2 dev 브랜치로 머지시 ECR로 이미지 push

.github/workflows/push_image_ecr.yml, .github/workflows/push_image_ecr_dev.yml, Dockerfile, README.md
Main branch update from Dev branch
=> Main branch update from Dev branch

src/components/Chatting/Chatting.jsx, src/components/Chatting/MessagesBody/ChatDate.jsx, src/components/Chatting/MessagesBody/ChatInOut.jsx, src/components/Chatting/MessagesBody/MessagesBody.jsx
=> #427 [Bug] 인피니트 스크롤 시에 채팅 깜빡임 현상

src/components/Home/InfoSection.tsx
It closes #431 
- 피그마 디자인대로 아이콘 추가하기
=> #431 홈페이지: 검색하기 <-> 개설하기

src/components/common/roomOptions/Date.tsx, src/components/common/roomOptions/DatePicker.jsx
=> #433 DatePicker에서 resize event 제거

cypress/utils/login.ts, src/components/AddRoom/AddRoom.tsx, src/components/Chatting/Chatting.jsx, src/components/Chatting/Header/Popup/PopupCancel.jsx, src/components/Chatting/Header/Popup/PopupPay.jsx, src/components/Chatting/Header/Popup/PopupSend.jsx, src/components/Home/RoomSection.tsx, src/components/Mypage/PopupPolicy.jsx, src/components/Myroom/R2Myroom.jsx, src/components/Search/RoomSelectionModal.jsx, src/components/Search/Search.jsx, src/components/Skeleton/Skeleton.tsx
=> #443 logininfo와 rooms api call 통일

src/components/Myroom/R1Myroom.tsx
=> #329 TypeScript component의 defaultProps 사용 지우기

src/serverconf.js, src/tools/firebase.ts
=> #475 [Bug] REACT_APP_FIREBASE_CONFIG 환경변수가 없으면 서비스 워커 추가 안함

src/hooks/useTaxiAPI/useAxios.tsx
=> #389.2 [Bug] logout 감지 안됨

src/hooks/useDateToken.tsx, src/hooks/useTaxiAPI/useQuery.tsx, src/pages/Chatting/index.jsx, src/pages/Home/RoomSection.tsx, src/pages/Mypage/index.jsx, src/pages/Myroom/R2Myroom.jsx
=> #491 Introduce `useDateToken`

src/App.js, src/components/Skeleton/ChannelTalkProvider/index.tsx, src/components/Skeleton/ScrollRestoration/index.tsx, src/components/Skeleton/index.tsx, src/components/SuggestLogin.tsx, src/hooks/useTaxiAPI/useAxios.tsx, src/pages/Addroom/index.tsx, src/pages/Error/PageNotFound.tsx, src/pages/Home/Date.tsx, src/pages/Home/InfoSection.tsx, src/pages/Home/RoomSection.tsx, src/pages/Home/SelectDate.tsx, src/pages/Home/index.tsx, src/pages/Login/Logout.tsx, src/pages/Login/index.jsx, src/pages/Search/RoomSelectionModal.jsx, src/tools/random/index.ts, src/tools/random/roomNames.js, src/tools/random/taxiSlogans.ts
It closes #501 
- 로그인 페이지를 "로그인이 필요한 페이지에 로그인 없이 접근 시 뜨는 에러 페이지"로 수정 후 부활시켰습니다.
- 홈페이지에서 "개인정보 처리방침" 모달을 띄울 수 있도록 조치하였습니다.
- 로그인 페이지 뿐만 아니라 에러페이지에서도 채널톡 버튼이 띄어지도록 하였습니다.
=> #501.2 로그인 페이지 부활

src/components/Skeleton/index.tsx, src/pages/Mypage/ModalNotification/index.tsx
=> #507 알림 조회 및 수정 시 Request에서 deviceToken 삭제

src/components/Empty.tsx, src/components/Footer.tsx, src/components/Skeleton/Footer.tsx, src/components/Skeleton/Navigation.tsx, src/components/Skeleton/index.tsx, src/components/Title.jsx, src/pages/Event/Event2022Beta.jsx, src/pages/Event/Event2023Spring.tsx, src/pages/Event/index.tsx, src/pages/Home/EventSection.tsx, src/pages/Home/InfoSection.tsx, src/pages/Home/RoomList.tsx, src/pages/Home/RoomSection.tsx, src/pages/Home/index.tsx, src/pages/Mypage/index.tsx, src/routes.ts
=> #526 홈페이지 Footer 추가

public/index.html
It closes #377 
- og meta tag 를 설정하였습니다.
```html
<meta property="og:url" content="%PUBLIC_URL%" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Taxi" />
<meta
property="og:description"
content="KAIST 구성원들의 택시 동승 인원 모집을 위한 서비스"
/>
<meta property="og:image" content="%PUBLIC_URL%/graph.png" />
<meta property="og:locale" content="ko_KR" />
<meta property="og:locale:alternate" content="en_US" />
```
- 설정 전
- 설정 후
- https://ogp.me/
- 안드로이드 앱 출시 후, og tag 설정
- IOS 앱 출시 후, og tag 설정
=> #377 Open Graph 설정

src/components/ModalRoomOptions/Picker.css
=> #536 Scroll Picker 투명 오류

package-lock.json, package.json, src/hooks/useTaxiAPI/useAxios.tsx, src/tools/day.ts
=> #541 `day.js` 도입

src/components/Footer.tsx, src/components/ModalPopup/Body/BodyRoomSelection.tsx, src/pages/Home/RoomSection.tsx, src/pages/Home/index.tsx
=> #544 [Bug] 출발 시각이 지난 방을 공유 링크로 접근 시, 모달이 뜨지 않음

src/atoms/loginInfo.ts, src/components/Link/LinkLogin.tsx, src/pages/Login/index.jsx
It closes #523 
Flutter에 `accessToken`과 `refreshToken`을 전달합니다.
=> #523.2 Flutter와 event 기반 통신

src/atoms/isApp.ts, src/components/Link/LinkLogin.tsx, src/components/Skeleton/FlutterEventCommunicationProvider.tsx, src/hooks/useFetchRecoilState/index.tsx, src/pages/Login/index.jsx, src/tools/sendEventToFlutter.ts
It closes #523 
Flutter에 `accessToken`과 `refreshToken`을 전달합니다.
=> #523.3 Flutter와 event 기반 통신

src/pages/Home/index.tsx
It closes #465.4
개인정보처리방침 링크 생성
=> #465.4 개인정보처리방침 링크 생성

src/pages/Home/InfoSection.tsx, src/pages/Home/index.tsx
It closes #564 
- 지금은 임의로 전체 날짜가 아닌 `YYYY-MM-DD`만 사용해서 비교하도록 하였지만 나중에는 timezone을 설정하면 좋겠습니다. 이 이슈를 위해 `moment-timezone`를 설치하는건 번거롭다고 느껴졌고 나중에 혹여나 moment가 아닌 다른 라이브러리를 쓸 경우 해결하면 될것 같습니다.
=> #564 [Bug] 홈페이지 "n일 후 출발 예정" 날짜 오류

src/pages/Event/Event2023Spring.tsx
=> #525.2 이벤트 홍보 페이지 개선

src/pages/Home/index.tsx
It closes #575 
이벤트가 끝남에 따라 홈페이지의 이벤트 홍보 페이지로 이동하는 버튼을 가립니다.
=> #575 이벤트 홍보 안내 페이지 가리기

src/components/Skeleton/index.tsx, src/tools/trans.js
=> #545.2 IOS 기기 모바일에서 홈 페이지 접근 시, 택시 앱 유도 창 띄우기

src/components/FlipButton.tsx, src/components/ModalRoomOptions/FlipButton.tsx, src/components/ModalRoomOptions/Place.jsx
=> #579 출발지 도착지 뒤집기 버튼 추가하기

serve/invite.html
=> #592.3 `invite.html`에서 `redirectPath` 오타 수정

src/components/ModalPopup/Body/BodyRoomShare.tsx
=> #592.4 카카오톡 공유하기에서 `ogServer` 오타 수정

src/components/Chat/MessagesBody/MessageSet/MessageArrival.tsx, src/components/Chat/MessagesBody/MessageSet/MessageDeparture.tsx, src/components/Chat/MessagesBody/MessageSet/index.tsx, src/hooks/chat/useBodyScrollControllerEffect.tsx, src/hooks/chat/useChatsForBody.tsx, src/tools/chat/chats.ts, src/types/chat.d.ts
It closes #618 
- 출발 15분 전 메시지
- 출발 한시간 후 메시지
=> #618 출발 15분전 메시지 수신

src/components/ModalPopup/ModalCredit.tsx, src/components/ModalPopup/ModalRoomSelection.tsx, src/components/Navigation.tsx, src/pages/Event/Event2023FallLeaderboard.tsx, src/pages/Event/Event2023FallStore/PublicNoticeContainer.tsx, src/pages/Event/Event2023FallStore/index.tsx, src/pages/Event/index.tsx, src/pages/Mypage/langs/en.json, src/pages/Mypage/langs/ko.json, src/static/members/index.ts, src/static/members/members.ts, src/static/members/members2023FallEvent.ts, src/static/members/members2023SpringEvent.ts, src/types/members.d.ts
It closes #621 
달토끼 상점의 목업 `Public Notice` 컴포넌트를 제작하였습니다.
=> #621.2 달토끼 상점 목업 `Public Notice` 컴포넌트 제작

src/components/Chat/MessageForm/InputText/BodyText.tsx, src/components/Loading.tsx, src/pages/Event/Event2023FallStore/PublicNoticeContainer.tsx
=> #638 [Bug] 사파리에서 채팅 MessageForm 에 한글 연달아 전송 시, 이전 입력이 같이 들어옴

src/hooks/skeleton/useFlutterEventCommunicationEffect.tsx, src/pages/Event/Event2023Fall.tsx
It closes #644 
앱에서 테스트를 위해 안내 페이지에서 목업 인스타그램 공유 버튼을 제작하였습니다.
=> #644.1 안내 페이지 목업 인스타그램 공유 버튼 제작

package.json, pnpm-lock.yaml, src/App.css, src/components/Event/BodyRandomBox/index.css, src/components/Event/BodyRandomBox/index.tsx, src/components/ModalPopup/ModalEvent2023FallItem.tsx, src/components/ModalPopup/ModalEvent2023FallRandomBox.tsx, src/pages/Event/Event2023FallMissions.tsx, src/pages/Event/Event2023FallStore/PublicNoticeContainer.tsx
=> #658 [Bug] 아이폰 사파리에서 랜덤박스 화질 저하

src/atoms/event2023FallInfo.ts, src/components/Event/BodyRandomBox/index.css, src/components/Event/WhiteContainerSuggestJoinEvent/index.tsx, src/components/ModalPopup/ModalEvent2023FallItem.tsx, src/components/ModalPopup/ModalEvent2023FallJoin.tsx, src/pages/Event/Event2023Fall.tsx, src/pages/Event/Event2023FallLeaderboard.tsx, src/pages/Event/Event2023FallMissions.tsx, src/pages/Event/Event2023FallStore/PublicNoticeContainer.tsx, src/pages/Event/Event2023FallStore/index.tsx, src/pages/Home/EventSection/EventSection2023Fall.tsx, src/tools/regExpTest.js
It closes #657 
한가위 송편 이벤트 참여가 가능하도록 수정하였습니다.
=> #657 한가위 송편 이벤트 시작

src/hooks/skeleton/useFlutterEventCommunicationEffect.tsx
It closes #634 #523 
`pushHistory` Flutter Event를 추가하였습니다.
- 해당 JS 코드 주입시 `react-router`의 페이지를 이동할 수 있습니다.
```js
window.dispatchEvent(new CustomEvent("pushHistory", {
detail: "/event/2023fall"
}));
```
https://github.com/sparcs-kaist/taxi-front/assets/69258815/94aa7847-a35a-4eba-bdea-98d6d9998567
=> #634 `pushHistory` Flutter Event 추가

src/pages/Event/Event2023FallHistory.tsx, src/types/event2023fall.d.ts
=> #623.5 Event History page

src/components/Link/LinkEvent2023FallInstagramStoryShare.tsx, src/hooks/event/useEvent2023FallQuestComplete.ts
It closes #633 
공유하기 모달을 띄었다 닫을 경우 퀘스트를 달성합니다.
=> #633.1 공유하기 퀘스트 달성

src/pages/Home/EventSection/EventSection2023FallResult.tsx, src/pages/Home/EventSection/index.tsx, src/tools/loadenv.ts
=> #680 한가위 송편 이벤트 종료

packages/web/vite.config.ts
=> [Bug] vite env 파일 작동 안함

packages/web/src/pages/Home/EventSection/index.tsx
=> #725.2 2024 봄학기 이벤트 스켈레톤 만들기

packages/web/src/atoms/event2024SpringInfo.ts, packages/web/src/pages/Home/EventSection/EventSection2024Spring.tsx
=> 새터반 택시 대제전 참여 대상자만 이벤트 표시

packages/web/src/pages/Event/Event2024SpringLeaderboard.tsx
=> Fix: 새터반 택스트 너비 고정

packages/web/src/hooks/skeleton/useChannelTalkEffect/channelService.js, packages/web/src/pages/Mypage/index.tsx
It closes #758 
`?channeltalk=true` 일 때 열어줌
=> #758 특정 쿼리에서 채널톡 창 열기

packages/web/src/tools/loadenv.ts
It closes #774
이슈에서 언급한 바와 같이, 이벤트 코드를 비활성화하였습니다.
- Nothing
=> #774 새터반 택시대제전 코드 비활성화

packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx
=> Fix: Issue solved

packages/web/src/components/ModalPopup/Body/BodyEvent2024FallAbuseWarning.tsx, packages/web/src/components/ModalPopup/Body/BodyEvent2024SpringAbuseWarning.tsx, packages/web/src/components/ModalPopup/ModalEvent2024FallAbuseWarning.tsx, packages/web/src/components/ModalPopup/index.tsx, packages/web/src/pages/Addroom/index.tsx
It closes #828 
- https://github.com/sparcs-kaist/taxi-back/pull/542 에 맞춰서 코드 수정
- recoilState 사용 등 코드 최적화 / 컨벤션에 맞게 수정
=> #828 2024 추석 이벤트: 어뷰징 경고 모달 수정

packages/web/src/pages/Home/EventSection/EventSection2024FallResult.tsx, packages/web/src/pages/Home/EventSection/index.tsx, packages/web/src/tools/loadenv.ts
It closes #838
- 홈 페이지에서 추첨 결과 컴포넌트 삭제
=> #838 2024 추석 이벤트: 종료 및 결과 발표

packages/web/src/tools/loadenv.ts
=> fix: build-error

packages/web/src/components/ModalPopup/ModalEvent2025SpringCoupon.tsx, packages/web/src/components/ModalPopup/index.tsx, packages/web/src/pages/Event/Event2025Spring.tsx, packages/web/src/tools/loadenv.ts, packages/web/src/tools/regExpTest.js
It closes #854 
- 에셋들을 이번 이벤트에 맞게 수정
=> #854 2025 봄 이벤트: 쿠폰 시스템

packages/web/src/components/ModalPopup/ModalChatPayment.tsx, packages/web/src/components/ModalPopup/ModalChatSaveAccount.tsx, packages/web/src/components/ModalPopup/ModalChatSettlement.tsx, packages/web/src/components/ModalPopup/ModalMypageModify.tsx, packages/web/src/components/ModalPopup/ModalNotification.tsx, packages/web/src/components/ModalPopup/ModalRoomShare.tsx
=> #861 [Bug] 일부 퀘스트가 달성되지 않거나, 퀘스트 달성 알림이 오지 않음

package.json, packages/web/src/pages/Event/Event2025SpringStore/Leaderboard.tsx
It closes #831 
공동 순위일 때 '나' 표시, 내가 20등 아래일 때 내 등수 표기 수정
=> 2025 새학기 이벤트 : 리더보드 순위 관련 수정

packages/web/src/components/Event/DailyAttendanceCalendar/index.tsx, packages/web/src/pages/Event/Event2025SpringDailyAttendance.tsx
=> #875 2025 새학기 이벤트 : 밸런스 게임 페이지 수정

Dockerfile, serve/default.conf
Reverts sparcs-kaist/taxi-front#870
=> Revert "#869 [Refactor] Docker 이미지 사이즈 줄이기"

packages/web/src/pages/Home/EventSection/index.tsx
It closes #883 
2025 새학기 이벤트 결과 공지 섹션을 홈페이지에서 더이상 보여주지 않습니다.
=> #883.2 2025 새학기 이벤트: 결과 섹션 삭제

packages/web/public/.well-known/apple-app-site-association
=> #923 원앱 Universal Link 지원을 위한 AASA 파일 추가

packages/web/src/components/ModalPopup/Body/BodyPrivacyPolicy.tsx
=> 개인정보 처리방침 개정
